// export const SET_ISLOGIN = "SET_ISLOGIN"
export const SET_MOBILE = "SET_MOBILE"
export const SET_USERNAME= "SET_USERNAME"
export const SET_ISAUTH= "SET_ISAUTH"
export const SET_TRUENAME= "SET_TRUENAME"
export const SET_PAYPASSWORD= "SET_PAYPASSWORD"
export const SET_INVITECODE= "SET_INVITECODE"
export const SET_IDCARD = "SET_IDCARD"
export const SET_IDCARDTYPE = "SET_IDCARDTYPE"
export const SET_REALNAME = "SET_REALNAME"
export const SET_AUTHTIME = "SET_AUTHTIME"
export const SET_TOKEN = "SET_TOKEN"
export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN"
export const SET_COUNTRYCODE = "SET_COUNTRYCODE"

// 创新交易
export const EXCHANGE_MARKETS = "EXCHANGE_MARKETS"
// 高级认证状态
export const SET_SENIOR_AUTH_STATUS= "SET_SENIOR_AUTH_STATUS"
export const SET_LANG= "SET_LANG"
export const SET_EXPIRE_TIME= "SET_EXPIRE_TIME"  //包含过期时间的token对象
export const SET_SENIOR_AUTH_DESC= "SET_SENIOR_AUTH_DESC"

export const SET_GA_STATUS= "SET_GA_STATUS"
export const SET_EMAIL= "SET_EMAIL"



