export const pageTitleMap = {
  "zh-CN":{
    1:"首页",
    2:"币币交易",
    3:"场外交易",
    4:"个人中心",
    5:"身份认证",
    6:"身份高级认证",
    7:"手机号码",
    8:"修改登录密码",
    9:"修改交易密码",
    10:"设置交易密码",
    11:"邀请奖励",
    12:"账户资产",
    13:"提现地址管理",
    14:"委托记录",
    15:"成交记录",
    16:"充值记录",
    17:"提现记录",
    18:"登录",
    19:"注册",
    20:"忘记密码",
    21:"重置交易密码",
    22:"完善用户信息",
    23:"创新交易",
    24:"关于我们",
    25:"帮助中心",
    26:"费率说明",
    27:"服务协议",
    28:"API文档",
    29:"上币申请",
    30:"工单系统"
  },
  "zh-HK":{
    1:"首頁",
    2:"幣幣交易",
    3:"場外交易",
    4:"個人中心",
    5:"身份認證",
    6:"身份高級認證",
    7:"手機號碼",
    8:"修改登錄密碼",
    9:"修改交易密碼",
    10:"設置交易密碼",
    11:"邀請獎勵",
    12:"賬戶資產",
    13:"提幣地址管理",
    14:"委託記錄",
    15:"成交記錄",
    16:"充值記錄",
    17:"提幣記錄",
    18:"登錄",
    19:"註冊",
    20:"忘記密碼",
    21:"重置交易密碼",
    22:"完善用戶信息",
    23:"創新交易",
    24:"關於我們",
    25:"幫助中心",
    26:"費率說明",
    27:"服務協議",
    28:"API文檔",
    29:"上幣申請",
    30:"工單系統"
  },
  "en-US":{
    1: "Home",
    2: "Currency Transactions",
    3: "OTC",
    4: "Personal Center",
    5: "authentication",
    6: "Identity Advanced Authentication",
    7: "Mobile number",
    8: "Modify Login Password",
    9: "Change transaction password",
    10: "Set transaction password",
    11: "Invitation to reward",
    12: "Account Assets",
    13: "Withdraw Address Management",
    14: "Delegation Record",
    15: "Transaction Records",
    16: "Recharge Record",
    17: "Withdrawal Record",
    18: "Login",
    19: "Registration",
    20: "Forgot your password",
    21: "Reset transaction password",
    22: "Perfect User Information",
    23: "Innovative Transactions",
    24: "About us",
    25: "Help Center",
    26: "Description of Rates",
    27: "Service Agreement",
    28: "API Documentation",
    29: "Apply for Currency",
    30: "Work Order System"
  }
}
